# Generated by Django 5.2.8 on 2025-12-24 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g., Dr., Professor, Ph.D.', max_length=50)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State or Province')),
                ('postal_code', models.CharField(max_length=20, verbose_name='ZIP or Postal Code')),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('professional_affiliation', models.CharField(help_text='Institution or organization name', max_length=255)),
                ('affiliation_type', models.CharField(choices=[('academic', 'Academic'), ('government', 'Government'), ('industry', 'Industry'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], default='academic', max_length=20)),
                ('membership_type', models.CharField(choices=[('professional', 'Professional'), ('retired', 'Retired Professional'), ('postdoc', 'Postdoc'), ('student', 'Student')], default='professional', max_length=20)),
                ('verification_method', models.CharField(choices=[('publications', 'Has published in peptide science'), ('sponsor', 'Will provide sponsor reference')], default='publications', help_text='How the applicant verifies their involvement in peptide science', max_length=20)),
                ('publications', models.TextField(blank=True, help_text='List of publications (citations or DOIs)')),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('sponsor_email', models.EmailField(blank=True, max_length=254)),
                ('sponsor_letter_received', models.BooleanField(default=False, help_text='Check when sponsor letter has been received')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection, if applicable')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to member)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
                'ordering': ['-applied_at'],
            },
        ),
    ]
