# Generated by Django 5.2.8 on 2025-12-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, help_text='Optional profile photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='symposia_attended',
            field=models.CharField(blank=True, help_text="Comma-separated list of symposium years attended (e.g., '2019,2022,2025')", max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP or Postal Code'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='professional_affiliation',
            field=models.CharField(blank=True, help_text='Institution or organization name', max_length=255),
        ),
    ]
