# Generated by Django 5.2.8 on 2025-12-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_memberprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatusToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status Check Token',
                'verbose_name_plural': 'Status Check Tokens',
            },
        ),
    ]
