<div class="col-md-12 page-header">
<h1 class="main-page-header">About the American Peptide Society</h1>
</div>
<div class="col-md-8 nopad">
<p>The American Peptide Society, APS, a nonprofit scientific and educational organization founded in 1990, provides a forum for advancing and promoting knowledge of the chemistry and biology of peptides. The approximately 2,100 members of the Society come from North America and from more than fifty-six other countries throughout the world. Establishment of the American Peptide Society was a result of the rapid worldwide growth that has occurred in peptide-related research, and of the increasing interaction of peptide scientists with virtually all fields of science.</p>
<p>The Society organizes a biennial international symposium featuring invited and submitted talks from distinguished scientists. The APS sponsors five awards, including the early-career investigator awards, and all awardees present lectures at the Symposium. The Symposium also provides a platform for graduate students to present their research in poster sessions, with several selected by the organizers for oral presentations.</p>
<p>Members of the American Peptide Society are involved in research in academia, industry, and government, covering all aspects of peptide chemistry, biology and materials. Research topics include design and synthesis of folded peptides, isolation, and characterization of peptide natural products, drug delivery, and the discovery of new biopolymers. Basic research in peptide synthesis and delivery has given way to the current excitement for peptides as drugs for diabetes, obesity and other diseases. The share of peptide therapeutics is expected to significantly grow over the next decade.</p>
<h2 class="secondary-header">Diversity, Equity, and Inclusion</h2>
<p>The American Peptide Society is firmly committed to fostering a community that is welcoming to peptide scientists with diverse life experiences, regardless of race, ethnicity, religion, national origin, disability, age, gender identity or expression, or sexual orientation. The APS strives for equity, diversity, and inclusion.</p>
<h2 class="secondary-header">International Peptide Societies</h2>
<p>[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.cps2024-international.cn/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Chinese Peptide Society</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.ozpeptide.org/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Australian Peptide Society</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.eurpepsoc.com" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">European Peptide Society</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://indianpeptidesociety.com" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Indian Peptide Society</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.peptide-soc.jp/en/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Japanese Peptide Society</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="http://kpps.or.kr/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Korean Peptide Society</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.gfpp.fr/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">French Peptide Society</span></a></p>
<h2 class="secondary-header">Other Related Links</h2>
<p>[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.boulderpeptide.org/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Boulder Peptide Foundation</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.rsc.org/membership-and-community/connect-with-others/through-interests/interest-groups/protein-and-peptide-science/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">British RSC Protein &amp; Peptide Science Group</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.grc.org/chemistry-and-biology-of-peptides-conference/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Gordon Research Conference: Chemistry and Biology of Peptides</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.nobcche.org/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">NOBCCHE</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://www.sacnas.org/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">SACNAS</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="https://peptidetherapeutics.org/symposium/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">Peptide Therapeutics Foundation</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a class="link" href="http://www.peptidelinks.net/" target="_blank" rel="noopener noreferrer"><span class="ul-link-text">PeptideLinks</span></a><br />
[gem_icon pack="fontawesome" icon_fontawesome="f0da" size="small" color="#3a5894"] <a href="https://www.postdocacademy.org/"><span class="ul-link-text">Postdoc Academy</span></a></div>
<div class="col-md-4 nopad"><p>[gem_button text="Become a Member!" corner="3" size="giant" size_tablet="medium" size_mobile="small" icon_pack="elegant" link="url:https%3A%2F%2Famericanpeptidesociety.org%2Fmembership-application%2F|title:Membership%20Application" text_color="#ffffff" background_color="#cb3b2d" hover_text_color="#ffffff" hover_background_color="#3a53a4" padding_left="29px" margin_top="0" margin_top_tablet="0" margin_top_mobile="0"]</p>
<p><img src="https://americanpeptidesociety.org/wp-content/uploads/2024/03/group_2.jpg" alt="Symposium image" style="margin-bottom: 29px;" class="img-responsive"><br />
<img src="https://americanpeptidesociety.org/wp-content/uploads/2024/03/group_image.jpg" alt="Symposium image" style="margin-bottom: 29px;" class="img-responsive"></div>
