# Generated by Django 5.2.8 on 2025-12-13 17:27

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Research Category',
                'verbose_name_plural': 'Research Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(help_text="Display title for cards, e.g., 'Modeling Selectivity'", max_length=100)),
                ('lab_name', models.CharField(help_text="Lab name for cards, e.g., 'Miller Lab'", max_length=100)),
                ('main_image_caption', models.TextField(blank=True, help_text='Caption for main figure (HTML allowed)')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='Date displayed on cards and used for ordering')),
                ('blurb', models.TextField(blank=True, help_text='Brief summary for archive listings and social sharing (not shown on homepage)')),
                ('body', wagtail.fields.RichTextField(help_text='Full synthesized article (HTML allowed, supports images)')),
                ('publication_title', models.CharField(help_text='Full title of the original journal article', max_length=500)),
                ('publication_authors', models.TextField(help_text='Author list from the publication')),
                ('publication_citation', models.CharField(help_text='Citation: Journal, Year, Volume, Pages (HTML allowed for italics)', max_length=300)),
                ('publication_url', models.URLField(help_text='DOI or journal link')),
                ('pi_first_name', models.CharField(max_length=100)),
                ('pi_last_name', models.CharField(max_length=100)),
                ('pi_title', models.CharField(blank=True, help_text="e.g., 'Professor', 'Associate Professor'", max_length=200)),
                ('pi_institution', models.CharField(help_text='Institution or company', max_length=300)),
                ('pi_url', models.URLField(blank=True, help_text="PI's lab or profile page")),
                ('author_1_info', models.TextField(blank=True, help_text='First author bio (HTML allowed)')),
                ('author_2_info', models.TextField(blank=True, help_text='Second author bio (HTML allowed)')),
                ('author_3_info', models.TextField(blank=True, help_text='Third author bio (HTML allowed)')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from short title', max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_1_image', models.ForeignKey(blank=True, help_text='First author photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('author_2_image', models.ForeignKey(blank=True, help_text='Second author photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('author_3_image', models.ForeignKey(blank=True, help_text='Third author photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('main_image', models.ForeignKey(blank=True, help_text='Main figure/graphic (recommended: 973x670px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('category', models.ForeignKey(blank=True, help_text='Category for archive page filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_items', to='home.researchitemcategory')),
            ],
            options={
                'verbose_name': 'Research Item',
                'verbose_name_plural': 'Research Items',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
