# Generated by Django 5.2.8 on 2025-12-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_researchitemcategory_researchitem'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymposiumGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introduction text for the gallery page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='body',
            field=models.TextField(help_text='Full synthesized article - paste raw HTML with inline styles'),
        ),
        migrations.CreateModel(
            name='SymposiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2015, '2015 - Orlando'), (2017, '2017 - Whistler'), (2019, '2019 - Monterey'), (2022, '2022 - Whistler'), (2023, '2023 - Boston'), (2025, '2025 - San Diego')])),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('photographer', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Symposium Image',
                'verbose_name_plural': 'Symposium Images',
                'ordering': ['-year', 'sort_order'],
            },
        ),
    ]
