# Generated by Django 5.2.8 on 2025-12-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_symposiumgallerypage_alter_researchitem_body_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeptideLinksIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introduction text for the page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Research Area',
                'verbose_name_plural': 'Research Areas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='symposiumimage',
            name='year',
            field=models.IntegerField(choices=[(2015, '2015 - Orlando'), (2017, '2017 - Whistler'), (2019, '2019 - Monterey'), (2022, '2022 - Whistler'), (2023, '2023 - Tucson'), (2025, '2025 - San Diego')]),
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text='e.g., Professor, Associate Professor', max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('state_province', models.CharField(blank=True, help_text='State (US) or Province (Canada)', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, help_text='Personal or lab website')),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID identifier (e.g., 0000-0000-0000-0000)', max_length=50)),
                ('pubmed_url', models.URLField(blank=True)),
                ('google_scholar_url', models.URLField(blank=True, help_text='Google Scholar profile URL')),
                ('research_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('is_active', models.BooleanField(default=True, help_text='Display in public directory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_areas', models.ManyToManyField(blank=True, related_name='researchers', to='home.researcharea')),
            ],
            options={
                'verbose_name': 'Researcher',
                'verbose_name_plural': 'Researchers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
