# Generated by Django 5.2.8 on 2025-12-15 13:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_peptidelinksindexpage_researcharea_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='APSCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'APS Committee',
                'verbose_name_plural': 'APS Committees',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APSRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('officer', 'Officer'), ('councilor', 'Councilor'), ('staff', 'Staff'), ('past_president', 'Past President')], max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (lower numbers first)')),
            ],
            options={
                'verbose_name': 'APS Role',
                'verbose_name_plural': 'APS Roles',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeopleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introduction text (two paragraphs separated by blank line)')),
            ],
            options={
                'verbose_name': 'People Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='APSPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('professional_title', models.CharField(blank=True, help_text='e.g., Professor, Associate Professor, Ph.D.', max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from public pages')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'APS Person',
                'verbose_name_plural': 'APS People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonCommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_role', models.CharField(choices=[('chair', 'Chair'), ('co_chair', 'Co-Chair'), ('member', 'Member')], default='member', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='home.apscommittee')),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='home.apsperson')),
            ],
            options={
                'verbose_name': 'Committee Membership',
                'verbose_name_plural': 'Committee Memberships',
                'ordering': ['committee__display_order', '-membership_role'],
            },
        ),
        migrations.CreateModel(
            name='PersonRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_start', models.DateField(blank=True, help_text='When this role began', null=True)),
                ('service_end', models.DateField(blank=True, help_text='When this role ended (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Currently holds this role')),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='home.apsperson')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='home.apsrole')),
            ],
            options={
                'verbose_name': 'Role Assignment',
                'verbose_name_plural': 'Role Assignments',
                'ordering': ['-is_current', '-service_start'],
            },
        ),
    ]
