# Generated by Django 5.2.8 on 2025-12-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_apscommittee_apsrole_peopleindexpage_apsperson_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Awards Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Short name for navigation buttons', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=200)),
                ('sponsor_description', models.TextField(blank=True)),
                ('sponsor_url', models.URLField(blank=True)),
                ('additional_content', models.TextField(blank=True, help_text='Additional content like essay links (HTML allowed)')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sponsor_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Award Type',
                'verbose_name_plural': 'Award Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AwardRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='home.awardtype')),
            ],
            options={
                'verbose_name': 'Award Recipient',
                'verbose_name_plural': 'Award Recipients',
                'ordering': ['-year', 'last_name'],
                'unique_together': {('award_type', 'year', 'last_name')},
            },
        ),
    ]
