# Generated by Django 5.2.8 on 2025-12-15 19:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_awardrecipient_slug_unique'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPeptideGroupIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introduction text for the archive page')),
            ],
            options={
                'verbose_name': 'Global Peptide Groups Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GlobalPeptideGroupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('lab_name', models.CharField(help_text="Full lab name (e.g., 'The Craik Group')", max_length=200)),
                ('pi_name', models.CharField(blank=True, help_text='Principal Investigator name', max_length=200)),
                ('institution', models.CharField(blank=True, help_text='Institution name', max_length=300)),
                ('blurb', models.TextField(blank=True, help_text='Short description for homepage/archive display')),
                ('feature_date', models.DateField(blank=True, help_text='Month/year when this group was featured', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Mark as currently featured group')),
                ('tabs', wagtail.fields.StreamField([('tab', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Tab title (e.g., 'WHO WE ARE', 'OUR RESEARCH')", 'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Raw HTML content for this tab. Supports Bootstrap columns, images, etc.'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {})}, help_text="Add tabs with content for this group's page")),
                ('old_url_slug', models.CharField(blank=True, help_text='Original WordPress URL slug for redirect setup', max_length=200)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Image shown on archive page and as banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Global Peptide Group Page',
                'verbose_name_plural': 'Global Peptide Group Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
