# Generated by Django 5.2.8 on 2025-12-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_global_peptide_groups'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InMemoriam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('blurb', models.TextField(blank=True, help_text='Short summary for the index page (HTML allowed)')),
                ('full_text', models.TextField(blank=True, help_text='Full obituary content (HTML allowed)')),
                ('display_order', models.IntegerField(default=0, help_text='Higher numbers appear first')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'In Memoriam Entry',
                'verbose_name_plural': 'In Memoriam Entries',
                'ordering': ['-display_order'],
            },
        ),
    ]
