# Generated by Django 5.2.8 on 2025-12-17 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_inmemoriam'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News item title/headline', max_length=200)),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='Used for ordering (newest first)')),
                ('external_url', models.URLField(blank=True, help_text='External URL (leave blank if using internal page)')),
                ('link_text', models.CharField(default='Read More', help_text='Button text for the link', max_length=50)),
                ('image', models.ForeignKey(blank=True, help_text='Image displayed above the title (fluid/responsive, no cropping)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('internal_page', models.ForeignKey(blank=True, help_text='Link to an internal page (leave blank if using external URL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-publish_date'],
            },
        ),
    ]
