# Generated by Django 5.2.8 on 2025-12-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_newsitem'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='body',
            field=models.TextField(blank=True, help_text='Text content displayed below the image (HTML allowed)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image displayed below the title (fluid/responsive, no cropping)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
