# Generated by Django 5.2.8 on 2025-12-17 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_newsitem_body_alter_newsitem_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostdocProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('position_title', models.CharField(help_text='e.g., Feodor Lynen Research Fellow', max_length=200)),
                ('lab_name', models.CharField(help_text='e.g., Suga Lab', max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('headshot_credit', models.CharField(blank=True, help_text='Photo credit (optional)', max_length=200)),
                ('lab_photo_caption', models.TextField(blank=True, help_text='Caption for lab photo')),
                ('homepage_blurb', models.TextField(help_text='~80 words for homepage card display')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='Used for ordering (newest first)')),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage')),
                ('body', models.TextField(help_text='Full synthesized profile - paste raw HTML with inline images')),
                ('personal_website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('google_scholar_url', models.URLField(blank=True)),
                ('headshot', models.ForeignKey(blank=True, help_text='Portrait photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('lab_photo', models.ForeignKey(blank=True, help_text='Lab or research photo (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Postdoc Profile',
                'verbose_name_plural': 'Postdoc Profiles',
                'ordering': ['-publish_date'],
            },
        ),
    ]
