# Generated by Django 5.2.8 on 2025-12-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_postdocprofile'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdocprofile',
            name='sidebar_image_3',
            field=models.ForeignKey(blank=True, help_text='Third sidebar image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='postdocprofile',
            name='sidebar_image_3_caption',
            field=models.TextField(blank=True, help_text='Caption for third image'),
        ),
        migrations.AddField(
            model_name='postdocprofile',
            name='sidebar_image_4',
            field=models.ForeignKey(blank=True, help_text='Fourth sidebar image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='postdocprofile',
            name='sidebar_image_4_caption',
            field=models.TextField(blank=True, help_text='Caption for fourth image'),
        ),
    ]
