# Generated by Django 5.2.8 on 2025-12-22 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_postdocprofile_sidebar_image_3_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('title', models.CharField(help_text="Spotlight title, e.g., 'Blocking Metastasis'", max_length=300)),
                ('program_info', models.CharField(help_text="e.g., 'Fourth-year Ph.D. Candidate in Chemistry'", max_length=200)),
                ('lab_name', models.CharField(help_text='e.g., Kennedy Lab', max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('headshot_credit', models.CharField(blank=True, help_text='Photo credit (optional)', max_length=200)),
                ('sidebar_image_2_caption', models.TextField(blank=True, help_text='Caption for second image')),
                ('homepage_blurb', models.TextField(help_text='~55 words for homepage card display')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='Used for ordering (newest first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage (only one should be featured at a time)')),
                ('body', models.TextField(help_text='Full profile - paste raw HTML with inline images')),
                ('personal_website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('google_scholar_url', models.URLField(blank=True)),
                ('headshot', models.ForeignKey(blank=True, help_text='Portrait photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('sidebar_image_2', models.ForeignKey(blank=True, help_text='Second sidebar image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-publish_date'],
            },
        ),
    ]
