# Generated by Django 5.2.8 on 2025-12-22 20:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_studentprofile'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Student Spotlight', 'verbose_name_plural': 'Student Spotlights'},
        ),
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Symposium year (e.g., 2025)', unique=True)),
                ('title', models.CharField(help_text="Symposium theme (e.g., 'Peptides Rising')", max_length=300)),
                ('venue_name', models.CharField(help_text="Venue name (e.g., 'Sheraton San Diego Hotel')", max_length=300)),
                ('location', models.CharField(help_text="City, State/Country (e.g., 'San Diego, CA')", max_length=200)),
                ('pdf_url', models.URLField(blank=True, help_text='URL to proceedings PDF on DigitalOcean Spaces')),
                ('chairs', wagtail.fields.StreamField([('chair', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Chair's full name", 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Institution or company', 'max_length': 300}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('affiliation', 1)]], {})}, help_text='Symposium co-chairs')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (higher numbers first)')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Symposium program cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Proceeding',
                'verbose_name_plural': 'Proceedings',
                'ordering': ['-year'],
            },
        ),
    ]
