# Generated by Django 5.2.8 on 2025-12-22 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_add_proceeding_model'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(help_text='Volume number (e.g., 117)')),
                ('issue', models.IntegerField(help_text='Issue number (e.g., 1)')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('wiley_url', models.URLField(blank=True, help_text='URL to this issue on Wiley Online Library')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Journal issue cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Journal Issue',
                'verbose_name_plural': 'Journal Issues',
                'ordering': ['-year', '-month'],
                'unique_together': {('volume', 'issue')},
            },
        ),
    ]
