# Generated by Django 5.2.8 on 2025-12-26 15:37

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_add_journal_issue_model'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeptidePrimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Full title, e.g., 'Peptide Synthesis for Beginners'", max_length=200)),
                ('short_title', models.CharField(help_text="Short title for navigation, e.g., 'SPPS Basics'", max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('homepage_blurb', models.TextField(help_text='~55 words for homepage card display')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage (only one should be featured at a time)')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='Used for ordering (newest first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField(blank=True, help_text='Optional introduction shown above the tabbed content')),
                ('homepage_image', models.ForeignKey(blank=True, help_text='Image for homepage card (recommended: 400x280)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Peptide Primer',
                'verbose_name_plural': 'Peptide Primers',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='PeptidePrimerTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Tab title, e.g., 'Getting Started'", max_length=100)),
                ('tab_id', models.SlugField(help_text="URL-friendly ID for the tab, e.g., 'getting-started'")),
                ('content', models.TextField(help_text='HTML content for this tab')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('primer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='home.peptideprimer')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
