# Generated by Django 5.2.8 on 2025-12-27 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_peptide_primer'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymposiaArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Symposium year (e.g., 2007)')),
                ('symposium_number', models.CharField(blank=True, help_text="Symposium number (e.g., '20th', '22nd')", max_length=10)),
                ('title', models.CharField(help_text="Full title (e.g., '20th American Peptide Symposium')", max_length=200)),
                ('location', models.CharField(blank=True, help_text="Location (e.g., 'Montreal, Quebec, Canada')", max_length=200)),
                ('folder_name', models.CharField(help_text="Folder name for static site (e.g., 'aps2007')", max_length=50)),
                ('theme', models.CharField(blank=True, help_text="Conference theme if known (e.g., 'Peptides for Youth')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Any notes about the archived site')),
                ('screenshot', models.ForeignKey(blank=True, help_text='Homepage screenshot (973x670 recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Symposia Archive',
                'verbose_name_plural': 'Symposia Archives',
                'ordering': ['-year'],
            },
        ),
    ]
