# Generated by Django 5.2.8 on 2025-12-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_add_symposia_archive'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardtype',
            name='namesake_description',
            field=models.TextField(blank=True, help_text='Biography of the person the award is named after'),
        ),
        migrations.AddField(
            model_name='awardtype',
            name='namesake_name',
            field=models.CharField(blank=True, help_text='Name of the person the award is named after', max_length=200),
        ),
        migrations.AddField(
            model_name='awardtype',
            name='namesake_photo',
            field=models.ForeignKey(blank=True, help_text='Photo of the award namesake', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
